config/routes.rb
Rails.application.routes.draw do

  root 'upload#index'

  post "/upload" => "upload#upload"

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :upload
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  has_many :sales
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/upload_controller.rb
require 'csv'

class UploadController < ApplicationController
  HEADERS = %w(customer description price units address provider)

  def index
    @uploads = Upload.all
  end

  def upload
    log_file = upload_params.tempfile
    @upload = Upload.create

    data_from_file(log_file).each do |sale_attrs|
      @upload.sales.create(sale_attrs)
    end

    redirect_to root_path
  end

  protected
  def upload_params
    params.require(:sale_file)
  end

  def data_from_file(file)
    data = CSV.read(file, col_sep: "\t")
    data.delete_at(0)

    data.map do |row|
      row.each_with_index.map do |value, index|
        Hash[ HEADERS[index], value ]
      end.reduce(&:merge)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Esplunka</title>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='stage' class='container'>

    <div class="header clearfix">
      <nav>
        <ul class="nav nav-pills pull-right">
          <li role="presentation" class="active"><a href="#">Home</a></li>
          <li role="presentation"><a href="/about">Sobre</a></li>
          <li role="presentation"><a href="mailto: paulopatto@paulopatto.com">Contato</a></li>
        </ul>
      </nav>

      <h3 class="text-muted">Splunka</h3>
    </div>


      <%= yield %>
  </div>
</body>
</html>

app/views/upload/_form.html.erb
<%= form_tag upload_path, method: :post, multipart: true, class: 'form-inline' do %>

  <label class="btn btn-primary btn-file glyphicon glyphicon-cloud-upload">
    <strong>Upload </strong>
    <%= file_field_tag :sale_file, style: 'display: none;', class: 'custom-upload-button' %>
  </label>

  <%= submit_tag :enviar %>
<% end %>

app/views/upload/index.html.erb
<div class='jumbotron'>
  <h1> Registro de vendas </h1>
</div>

<%= render partial: 'form' %>

<hr />

<% if @uploads.empty? %>
  <em> Sem dados de vendas </em>
<% else %>
  <table class='table-striped'>
    <tr>
      <th>#</th>
      <th>Cliente</th>
      <th>Preço</th>
      <th>Unidades</th>
      <th>Endereços</th>
      <th>Fornecedor</th>
    </tr>
    <% @uploads.each do |upload| %>
      <% upload.sales.each do |sale| %>
        <tr>
          <td> <%= sale.id %> </td>
          <td> <%= sale.description %> </td>
          <td> <%= sale.price %> </td>
          <td> <%= sale.units %> </td>
          <td> <%= sale.address %> </td>
          <td> <%= sale.provider %> </td>
        </tr>
      <% end %>
      <tr>
        <td>Total</td>
        <td colspan=5>
          <span class='pull-rigth'>R$ <%= upload.sales.map{|s| s.price * s.units}.reduce(:+) %></span>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>